name: Feature Test

on:
  push:
    branches:
    - feature/**

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: pip cache
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
    - name: Install
      run: |
        python -m pip install -U pip
        pip install -r requirements_dev.txt
    - name: pytest
      run: pytest
